### ISSUE TITLE
NBT Issue with Too Many Entities

### ISSUE THREAD

**Issue by TorinnTheDragon** [TechReborn/RebornCore#110]
So I was running a server and woke up to this crash over at https://pastebin.com/mqaeBz6K one day and couldn't get the server back up and running.

I did find a temporary fix to boot the server back up was that I had to delete a whole folder named tme in the Worlds folder under ( [ */(World Name)/ ] ).

**Comment by kreezxil** [comment]
oh thanks for this answer. I'm going to do that now.

I also woke up to a server that was crashing repeatedly, the following are all technically the same, but maybe there is enough difference or similarity to bring insight.

http://paste.ubuntu.com/p/v5JtwtnHMC/
http://paste.ubuntu.com/p/Kt4RGTcvj9/
http://paste.ubuntu.com/p/xbZR6xGFFv/
http://paste.ubuntu.com/p/4XhXZ64Kmb/
http://paste.ubuntu.com/p/bbsZ2Nt99X/
http://paste.ubuntu.com/p/WfVtfdQkKm/
http://paste.ubuntu.com/p/JCGt4KdVHr/
http://paste.ubuntu.com/p/P9nnVwFk5P/
http://paste.ubuntu.com/p/QJVkdqKm84/
http://paste.ubuntu.com/p/dHjbsPjc66/
http://paste.ubuntu.com/p/B5NPwvjGFf/

I'm using FORGE build 2825 (1.12.2) and it's in the World of Dragons modpack (my pack).
Mod version: 1.12.2-1.0.0.1

**Comment by kreezxil** [comment]
This fix didn't entirely work, I did get the server running again, however I'm still greeted with this in console

```
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ConcurrentModificationException
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:32)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.nbt.CompressedStreamTools.func_74795_b(CompressedStreamTools.java:152)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at me.modmuss50.tme.data.DataManager$WorldDataManager.lambda$saveData$1(DataManager.java:139)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
[12:03:55] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:      at java.lang.Thread.run(Thread.java:748)
```

and it is preceded by a whole lot of 


```
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
[12:03:10] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already
```

server latest.log http://paste.ubuntu.com/p/sxYzyyt576/

**Comment by kreezxil** [comment]
it happened again, so sad. :(

server crash report: http://paste.ubuntu.com/p/2GH3FMhxqk/
server latest log: http://paste.ubuntu.com/p/hHJGFRnN9y/
server debug.log: http://paste.ubuntu.com/p/P4pJwmcsrW/

I suspect that I will continue to have these issues, so I'll stop adding to this for now unless I find a solution that works.

**Comment by modmuss50** [comment]
It’s not an issue with reborn core. I don’t have time to work on this mod, I would remove it from your mods, and I will remove it from curse as it doesn’t work

**Comment by kreezxil** [comment]
ok, weird, because on one server it is working nicely and on the one i'm reporting it's failing horribly. are you sure it doesn't work, is what i'm seeing an illusion. 

I see the blocks and items on the ground become one gray block. and the lag is drastically reduced.
