### ISSUE TITLE
Error during initialization, fails to load url from nonexistent domain files.modmuss50.me

### ISSUE THREAD

**Issue by serpi90** [TechReborn/RebornCore#140]
Looks like it loads ok after that. But shouldn't happen afaik
Mods (subset):
- fabric-api-0.4.29+build.290-1.15
- fabric-language-kotlin-1.3.61+build.1
- RebornCore-1.15-4.2.1+build.91
- TechReborn-1.15-3.3.1+build.167

```text/plain
[23:49:26] [Thread-76/INFO]: [STDERR]: java.net.UnknownHostException: files.modmuss50.me
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at java.net.Socket.connect(Socket.java:607)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at reborncore.common.shields.json.ShieldJsonLoader.lambda$load$1(ShieldJsonLoader.java:86)
[23:49:26] [Thread-76/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)```

**Comment by modmuss50** [comment]
I have shutdown that server. I will remove the code that tries to connect to it soon. It should be safe to ignore it for now
