### ISSUE TITLE
Crash Reborn-core with TechReborn 1.9.4

### ISSUE THREAD

**Issue by vVwd** [TechReborn/RebornCore#17]
Crashing on latest and previous version of Forge.

RebornCore-1.9-2.3.3.86-universal.jar (wrong version, I suppose?)
TechReborn-1.9.4-1.2.0.3-universal.jar
forge-1.9.4-12.17.0.1910-1.9.4

2016-05-22 13:41:08,014 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-22 13:41:08,018 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[13:41:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[13:41:08] [main/INFO] [FML]: Forge Mod Loader version 12.17.0.1909 for Minecraft 1.9.4 loading
[13:41:08] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[13:41:08] [main/WARN] [FML]: The coremod com.olafski.fastleafdecay.FldLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/WARN] [FML]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/WARN] [FML]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/WARN] [FML]: The coremod reborncore.asm.RebornASM does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/INFO] [RebornCore]: Loading RebornCore ASM
[13:41:08] [main/WARN] [FML]: The coremod atomicstryker.stalkercreepers.common.SCFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:41:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:41:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:41:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:41:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2016-05-22 13:41:13,429 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-22 13:41:13,483 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-22 13:41:13,500 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[13:41:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:41:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:41:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[13:41:13] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:41:15] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:56]: Completely ignored arguments: [--nativeLauncherVersion, 301]
[13:41:16] [Client thread/INFO]: Setting user: Hellsgator
[13:41:16] [Client thread/INFO] [RebornCore]: Found item class
[13:41:16] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/item/Item
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:62) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:57) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ng.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:533) ~[ko.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.Item
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:62) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:57) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ng.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:533) ~[ko.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer reborncore.asm.RebornClassTransformer@a20b94b from coremod Reborn Core ASM
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.9.4-12.17.0.1909-1.9.4.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:62) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:57) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ng.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:533) ~[ko.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at reborncore.asm.RebornClassTransformer.transform(RebornClassTransformer.java:48) ~[RebornClassTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.9.4-12.17.0.1909-1.9.4.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:62) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:57) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ng.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:533) ~[ko.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:41:16] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by vVwd** [comment]
Never mind. Wrong version. Case closed.

**Comment by modmuss50** [comment]
Gald you got it sorted, you were using the 1.9 version not 1.9.4

**Comment by vVwd** [comment]
There is no link on CurseForge, only 1.9. Fished it out of the files folder
on CurseForge.

Eyes are wonderful things to use sometimes. ;)

2016-05-22 14:21 GMT+02:00 Modmuss50 <notifications@github.com>:
