### ISSUE TITLE
[1.9.4] Getting spammed with "API is loaded from an incompatible class loader"

### ISSUE THREAD

**Issue by gabizou** [TechReborn/RebornCore#26]
In both IDE and in production environments I get this at launch:
```
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: * The API reborncoreAPI from source /Tools/Sponge/SpongeForge/run/mods/RebornCore-1.9.4-2.5.1.35-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:94)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:154)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:212)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:501)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)...
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: * The API reborncoreAPI from source /Tools/Sponge/SpongeForge/run/mods/RebornCore-1.9.4-2.5.1.35-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:94)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:154)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:212)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:501)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)...
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: * The API reborncoreAPI from source /Tools/Sponge/SpongeForge/run/mods/RebornCore-1.9.4-2.5.1.35-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:94)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:154)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:212)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:501)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)...
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: ****************************************
[12:02:15] [Client thread/WARN] [FML]: * The API CoFHAPI from source /Tools/Sponge/SpongeForge/run/mods/RebornCore-1.9.4-2.5.1.35-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:94)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:154)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:212)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:501)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
[12:02:15] [Client thread/WARN] [FML]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)...
[12:02:15] [Client thread/WARN] [FML]: ****************************************
```
I'm not entirely sure what this is actually meaning, but any suggestions would help. Yes, this is with SpongeForge.

**Comment by modmuss50** [comment]
I think I know what the issue is, I will fix this when I have some time

**Comment by HenryLoenwind** [comment]
Is this the same thing that makes runtime-deobf not work on it?

```
java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77978_p()Lnet/minecraft/nbt/NBTTagCompound;
	at techreborn.items.armor.ItemLithiumBatpack$$BasePowerTrait.getOrCreateNbtData(BasePowerTrait.java:88)
	at techreborn.items.armor.ItemLithiumBatpack$$BasePowerTrait.getEnergy(BasePowerTrait.java:15)
	at reborncore.common.powerSystem.PoweredItem.getEnergy(PoweredItem.java:69)
	at techreborn.items.armor.ItemLithiumBatpack.getDurabilityForDisplay(ItemLithiumBatpack.java:108)
	at net.minecraft.client.renderer.RenderItem.renderItemOverlayIntoGUI(RenderItem.java:431)
```

**Comment by modmuss50** [comment]
You need to use the proper debof builds found at: http://modmuss50.me:8080/job/RebornCore/ as JTraits doesn't work with it
