### ISSUE TITLE
[1.9.4] Huge lag spikes with JEI

### ISSUE THREAD

**Issue by alexgeek** [TechReborn/RebornCore#28]
Haven't got into this mod much so not sure what's trying to get rendered.
I'm assuming you're grabbing skins or something similar from the minecraft servers and not properly caching them?

```
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:147) [aqo.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java:74) [bnb.class:?]
	at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:85) [RebornItemStackRenderer.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:185) [brw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:438) [brw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:477) [brw.class:?]
	at mezz.jei.gui.ingredients.GuiItemStackFast.renderSlow(GuiItemStackFast.java:149) [GuiItemStackFast.class:?]
	at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:139) [GuiItemStackFastList.class:?]
	at mezz.jei.gui.ItemListOverlay.drawScreen(ItemListOverlay.java:288) [ItemListOverlay.class:?]
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:81) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_384_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:582) [bez.class:?]
	at mezz.jei.gui.RecipesGui.drawGuiContainerBackgroundLayer(RecipesGui.java:218) [RecipesGui.class:?]
	at mezz.jei.gui.RecipesGui.func_73863_a(RecipesGui.java:141) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at Reflector.callVoid(Reflector.java:304) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1398) [bnd.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bcd.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

```

**Comment by modmuss50** [comment]
Are you using any other mods?

**Comment by alexgeek** [comment]
Yes but there aren't any others in the stacktrace so I doubt its a conflict with them.
Here's the list:

```
  Bagginses-1.9.4-2.4.2b
  Baubles-1.9.4-1.2.1.0
  BiomesOPlenty-1.9.4-4.1.0.2025-universal
  BloodMagic-1.9.4-2.0.1-43
  BloodMagic-1.9.4-2.0.1-42.jar
  Bookshelf-1.9.4-1.2.3.273
  Botania-unofficial.r1.8-308
  Chameleon-1.9-2.1.4
  chiselsandbits-10.5
  chiselsandbits-10.2.jar
  deepresonance-1.9.4-1.2.0beta33
  deepresonance-1.9.4-1.1.4beta32.jar
  ElecCore-1.9.4-1.5.285
  EnderIO-1.9.4-3.0.0.40_alpha
  EnderCore-1.9.4-0.4.0.24-alpha
  EnderCore-1.9.4-0.4.0.21-alpha.jar
  EnderIO-1.9.4-3.0.0.35_alpha.jar
  environmentaltech-1.9.4-0.9.3c
  extrautils2-1.9.4-alpha-1.0.0a
  industrialcraft-2-2.5.18-ex19
  industrialcraft-2-2.5.13-ex19.jar
  inventorysorter-1.9.4-0.9.0+40.jar
  ironchest-1.9.4-6.0.144.786
  ironchest-1.9.4-6.0.142.784.jar
  jei_1.9.4-3.4.0.202
  LLOverlayReloaded-1.0.7-mc1.9.4
  Mantle-1.9.4-0.10.1.jenkins142
  mcjtylib-1.9.4-1.9.0
  mcjtylib-1.9.4-1.8.7.jar
  notenoughwands-1.9.4-1.3.4
  OptiFine_1.9.4_HD_U_B4
  ProgressiveAutomation-1.9.4-1.6.46
  ProjectE-1.9.4-PE1.0.3B
  Psi-beta-33
  Quark-beta-24
  Quark-beta-23.jar
  RebornCore-1.9.4-2.5.4.47-universal
  rftools-1.9.4-4.60
  rftoolsdim-1.9.4-4.30beta42
  rftools-1.9.4-4.49.jar
  rftoolsdim-1.9.4-4.23beta40.jar
  inventorysorter-1.9.4-0.9.1+41
  StorageDrawers-1.9-3.1.7
  TechReborn-1.9.4-1.3.2.120-universal
  TConstruct-1.9.4-2.3.1.jenkins229
  TombManyGraves-1.9.4-2.0.1
  valkyrielib-1.9.4-0.9.4
  Waila-1.7.0-B3_1.9.4
```

**Comment by modmuss50** [comment]
That error is not coming from RebornCore (Even though its in the stack trace) A mod is trying to render TileEntitySkull in JEI. So it could well be another mod that isnt mentioned in the stack trace. Could you look in JEI for player heads or mob heads. If you don't find anything I can investigate further.

**Comment by alexgeek** [comment]
There are player heads in JEI actually, seems to be the issue. 
Some mod is putting in player heads that look like mobs and blocks like pumpkins etc.
Not sure which is doing it. A temporary solution is to hide them in JEI but that doesn't seem to save.

**Comment by wesleybruce** [comment]
I've tried three packs with techreborn and reborn core and found the lag problem makes all three unplayable. It goes away if you disable both techreborn and reborn core. 
I'm building an exclusion pack to work though the variables. The impact on the 1.10.2 hermitcraft mod pack makes it unplayable in single player but live streams show that its not effecting multiplayer, is that a clue?
