### ISSUE TITLE
Netty kicks on right click of multiblock

### ISSUE THREAD

**Issue by thundR** [TechReborn/RebornCore#56]
For rebornstorage:

java.lang.NullPointerException: Undefined message for discriminator 6 in channel rebornCore
at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:99) ~[FMLIndexedMessageToMessageCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[minecraft_server.1.12.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[minecraft_server.1.12.jar:?]

Kicks one player, but the other can right click it fine, brings the GUI up properly.

**Comment by Kilmatar** [comment]
same here
MK1.12, RebornCore 1.12.1-3.3.0.99
https://pastebin.com/wcexSws7

**Comment by modmuss50** [comment]
Should be fixed now
