### ISSUE TITLE
Netty kicks when teleporting to an area with steves carts tree farm. Happenend on ATM3 V3.1

### ISSUE THREAD

**Issue by megalous** [TechReborn/RebornCore#66]
RebornCore-1.12.1-3.2.7.95
StevesCarts-1.12.1-2.4.7.40

I have a Steve's Carts running in a tree farm, it is supposed to drop off from its storage chest to the cargo manager on red and pick up charcoal for the coal engine on the blue side, inventories in the cargo manager are split into colours, below the cargo manager is an external distributor which is connected to TE ducts with a reinforced servo that pulls from below the distributor and a filter that puts charcoal back through the green side of the distributor. 
I teleported to the world spawn with FTB Utilities command and teleported back to my home  with FTB Utilities. My home teleport is not inside the spawn chunks and not chunkloaded, but claimed with FTB Utilities.
Upon loading the chunks the connection to the server terminates with the message: "A fatal error has occurred, this connection is terminated"
Since then i get this error every time i join the server.

Last few lines of the fml-junk-earlystartup.log, this is the only place i can see the error, read:
[The full logs are available here, they are pretty big14MB](https://gist.github.com/megalous/b7e3a236087d3a8c5ad38bb9c3c73f83)

Caused by: java.lang.NullPointerException: Undefined message for discriminator 9 in channel rebornCore
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:99) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	... 65 more
[11:14:35] [Netty Epoll Client IO #0/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[11:14:35] [Netty Epoll Client IO #0/INFO] [Astral Sorcery]: [AstralSorcery] Disconnected from server. Cleaning client cache.
[11:14:35] [Netty Epoll Client IO #0/INFO] [waterstrainer]: Importing waterstrainer_loottables.cfg ...
[11:14:35] [Netty Epoll Client IO #0/INFO] [waterstrainer]: No errors were found!
[11:14:47] [Session-Validator/INFO] [ReAuth]: Session validation successful

**Comment by megalous** [comment]
I seems to have resolved itself after a server restart.
