### ISSUE TITLE
[Reappearance] The API cofhapi from source ... 

### ISSUE THREAD

**Issue by MarkTwoFive** [TechReborn/RebornCore#71]
Hello there,

The issue #26 seems to be back:
```
[19:14:33] [Server thread/WARN] [FML]: ****************************************
[19:14:33] [Server thread/WARN] [FML]: * The API cofhapi from source <serverpath>\mods\1.10.2\RebornCore-1.10.2-2.13.6.142-universal.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:532)
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[19:14:33] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)...
[19:14:33] [Server thread/WARN] [FML]: ****************************************
```
As you can see I'm using TR 2.13.6.142 for MC 1.10.2.
I'm also running:
* Forge 1.10.2 - 12.18.3.2511
* SpongeForge 1.10.2 - (against f2477) API 5.2.0 build 2731
* JRE 1.8.0 update 151

I am aware that builds for 1.10.2 are mostly considered outdated but currently it's already hard to build mod packs at this version and going higher does not contribute to make things easier.
Due to that please excuse if that's not happening on versions above 1.10.2.

Kind regards,

Mark

**Comment by modmuss50** [comment]
Does this prevent the game from running? If not it can be ignored I think.

**Comment by MarkTwoFive** [comment]
I does not but having "This will not work" displayed in full caps suggests that this may cause issues.

**Comment by modmuss50** [comment]
I would suggest to ignore it, I dont believe its present in newer versions.

**Comment by MarkTwoFive** [comment]
I'd say I'll come back if this happens to cause issues.

**Comment by modmuss50** [comment]
Yep, let me know if you have any issues. Thanks.
