### ISSUE TITLE
Client NPE on trying to look some TR machines recipes in JEI

### ISSUE THREAD

**Issue by Bulldog83** [TechReborn/RebornCore#90]
Minecraft 1.12.2
Forge 14.23.4.2739
RebornCore 3.10.0.332
TechReborn 2.17.1.786
JEI 4.12.0.215

Crash log for centrifuge: https://gist.github.com/Bulldog83/439d9f966440b8f016aee3a8354f855f

For electorlizer:
```
java.lang.NullPointerException
    at reborncore.common.powerSystem.PowerSystem.getRoundedString(PowerSystem.java:133)
    at reborncore.common.powerSystem.PowerSystem.getLocaliszedPowerFormatted(PowerSystem.java:85)
    at techreborn.compat.jei.industrialElectrolyzer.IndustrialElectrolyzerRecipeWrapper.drawInfo(IndustrialElectrolyzerRecipeWrapper.java:66)
    at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:158)
    at mezz.jei.gui.recipes.RecipesGui.drawScreen(RecipesGui.java:215)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3938)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by modmuss50** [comment]
see https://github.com/TechReborn/RebornCore/pull/91
